analogdevicesinc/imu-ros2

- include/imu_ros2/acceleration_data_provider.h
- include/imu_ros2/acceleration_data_provider_interface.h
- include/imu_ros2/acceleration_ros_publisher.h
- include/imu_ros2/acceleration_ros_publisher_interface.h
- src/acceleration_data_provider.cpp
- src/acceleration_ros_publisher.cpp
- src/imu_ros2_node.cpp
- test/CMakeLists.txt
- test/src/acceleration_subscriber_test.cpp
> Ros 309 read acceleration

- CMakeLists.txt
- include/imu_ros2/static_data_provider.h
- include/imu_ros2/static_data_provider_interface.h
- include/imu_ros2/static_ros_publisher.h
- include/imu_ros2/static_ros_publisher_interface.h
- msg/StaticData.msg
- package.xml
- src/imu_ros2_node.cpp
- src/static_data_provider.cpp
- src/static_ros_publisher.cpp
- test/CMakeLists.txt
- test/package.xml
- test/src/static_subscriber_test.cpp
Created publisher that publish static data like firmware and product id
> Ros 308 read static data

- include/imu_ros2/data_provider_interface.h
- include/imu_ros2/data_provider_string.h
- src/acceleration_ros_publisher.cpp
- src/data_provider_string.cpp
- src/imu_ros2_node.cpp
- src/ros_subscriber_1.cpp
- src/static_ros_publisher.cpp
> Ros 315 configurable data

- include/imu_ros2/acceleration_data_provider.h
- include/imu_ros2/iio_wrapper.h
- src/acceleration_data_provider.cpp
- src/iio_wrapper.cpp
Signed-off-by: Vasile Holonec <Vasile.Holonec@analog.com>
> Added accelerometer wrapper for libiio

- CMakeLists.txt
- include/imu_ros2/gyroscope_data_provider.h
- include/imu_ros2/gyroscope_data_provider_interface.h
- include/imu_ros2/gyroscope_ros_publisher.h
- include/imu_ros2/gyroscope_ros_publisher_interface.h
- include/imu_ros2/iio_wrapper.h
- msg/GyroscopeData.msg
- src/gyroscope_data_provider.cpp
- src/gyroscope_ros_publisher.cpp
- src/iio_wrapper.cpp
- src/imu_ros2_node.cpp
- test/CMakeLists.txt
- test/src/gyroscope_subscriber_test.cpp
> Ros 310 gyroscope topic

- CMakeLists.txt
- include/imu_ros2/iio_wrapper.h
- src/iio_wrapper.cpp
Added another implementation using libiio api.
> Ros 325 wrapper optimized

- CMakeLists.txt
- src/iio_wrapper.cpp
- test/CMakeLists.txt
Added scale factor to acceleration and gyroscope
> Ros 328 add scale factor

- CMakeLists.txt
- include/imu_ros2/adiimu_data_provider.h
- include/imu_ros2/adiimu_data_provider_interface.h
- include/imu_ros2/adiimu_ros_publisher.h
- include/imu_ros2/adiimu_ros_publisher_interface.h
- include/imu_ros2/iio_wrapper.h
- msg/AdiImuData.msg
- package.xml
- src/adiimu_data_provider.cpp
- src/adiimu_ros_publisher.cpp
- src/iio_wrapper.cpp
- src/imu_ros2_node.cpp
- test/CMakeLists.txt
- test/src/adiimu_subscriber_test.cpp
Added a publisher that publish all sensors data.
> Ros 329 sbg imu data publisher

- src/acceleration_data_provider.cpp
- src/acceleration_ros_publisher.cpp
- src/adiimu_data_provider.cpp
- src/adiimu_ros_publisher.cpp
- src/gyroscope_ros_publisher.cpp
- src/imu_ros2_node.cpp
- src/ros_subscriber_1.cpp
- src/static_ros_publisher.cpp
> Increased topic speed

- include/imu_ros2/iio_wrapper.h
- src/adiimu_ros_publisher.cpp
- src/iio_wrapper.cpp
Scale factor is read once because is constant
> Ros 331 read scale once

- include/imu_ros2/acceleration_data_provider.h
- include/imu_ros2/acceleration_data_provider_interface.h
- include/imu_ros2/adiimu_data_provider.h
- include/imu_ros2/adiimu_data_provider_interface.h
- include/imu_ros2/iio_wrapper.h
- msg/AdiImuData.msg
- src/acceleration_data_provider.cpp
- src/acceleration_ros_publisher.cpp
- src/adiimu_data_provider.cpp
- src/adiimu_ros_publisher.cpp
- src/gyroscope_ros_publisher.cpp
- src/iio_wrapper.cpp
Make channels reading with buffer
> Ros 336 optimize reading

- CMakeLists.txt
- config/imu_config.yaml
- include/imu_ros2/acceleration_data_provider.h
- include/imu_ros2/acceleration_data_provider_interface.h
- include/imu_ros2/acceleration_ros_publisher.h
- include/imu_ros2/adiimu_ros_publisher.h
- include/imu_ros2/iio_wrapper.h
- include/imu_ros2/imu_control_parameters.h
- include/imu_ros2/imu_diag_data_provider.h
- include/imu_ros2/imu_diag_ros_publisher.h
- include/imu_ros2/imu_identification_ros_publisher.h
- include/imu_ros2/setting_declarations.h
- src/acceleration_data_provider.cpp
- src/acceleration_ros_publisher.cpp
- src/adiimu_data_provider.cpp
- src/adiimu_ros_publisher.cpp
- src/iio_wrapper.cpp
- src/imu_control_parameters.cpp
- src/imu_diag_data_provider.cpp
- src/imu_diag_ros_publisher.cpp
- src/imu_identification_data_provider.cpp
- src/imu_identification_ros_publisher.cpp
- src/imu_ros2_node.cpp
The imu control values was set as ros parameter.
You can change a parameter with the command
`ros2 param set imu_ros2_node linear_acceleration_compensation 0`
> Added imu control ros parameters

- CMakeLists.txt
- include/imu_ros2/accelgyrotemp_data_provider.h
- include/imu_ros2/accelgyrotemp_data_provider_interface.h
- include/imu_ros2/accelgyrotemp_ros_publisher.h
- include/imu_ros2/accelgyrotemp_ros_publisher_interface.h
- msg/AccelGyroTempData.msg
- src/accelgyrotemp_data_provider.cpp
- src/accelgyrotemp_ros_publisher.cpp
- src/imu_ros2_node.cpp
Added accel gyro temp publisher with buffer read
> Added accel gyro temp publisher

- src/iio_wrapper.cpp
- src/imu_ros2_node.cpp
> Detect device automatically

- include/imu_ros2/iio_wrapper.h
- src/iio_wrapper.cpp
- src/imu_control_parameters.cpp
Added new commands to device adis1657x
> Added new commands to device 77

- include/imu_ros2/acceleration_data_provider.h
- include/imu_ros2/acceleration_data_provider_interface.h
- include/imu_ros2/imu_diag_data_provider.h
- include/imu_ros2/imu_diag_data_provider_interface.h
- include/imu_ros2/imu_identification_data_provider.h
- include/imu_ros2/imu_identification_data_provider_interface.h
- include/imu_ros2/velangtemp_data_provider.h
- include/imu_ros2/velangtemp_data_provider_interface.h
- src/acceleration_data_provider.cpp
- src/acceleration_ros_publisher.cpp
- src/imu_diag_data_provider.cpp
- src/imu_diag_ros_publisher.cpp
- src/imu_identification_data_provider.cpp
- src/imu_identification_ros_publisher.cpp
- src/velangtemp_data_provider.cpp
- src/velangtemp_ros_publisher.cpp
Changed getData function signature
> Changed getData function signature

- CMakeLists.txt
- include/imu_ros2/iio_wrapper.h
- src/iio_wrapper.cpp
- src/imu_16505_diag_ros_publisher.cpp
- test/CMakeLists.txt
- test/src/imu_16505_diag_subscriber_test.cpp
- test/src/imu_subscriber_test.cpp
- test/src/velangtemp_subscriber_test.cpp
Update imu 16505 diag test and imu test
> Update imu 16505 diag test and imu test

- src/imu_control_parameters.cpp
> Fix accel_calibbias_z range

- CMakeLists.txt
- README.rst
- launch/imu_tof_fusion.launch.py
- launch/imu_with_madgwick_filter_rviz.launch.py
- rviz/imu_tof_fusion.rviz
- rviz/imu_with_madgwick_filter_rviz.rviz
Add launch files:
- imu with madgwick filter and rviz
- tof and imu sensor fusion with rviz
Update the documentation accordingly.
> Add launch files

- src/iio_wrapper.cpp
Add trigger index numbering equal to the iio device index.
> Add trigger index numbering equal to the iio device index.

- include/imu_ros2/iio_wrapper.h
- src/iio_wrapper.cpp
- src/imu_ros2_node.cpp
PR:
* changed order of thread starts
* added exit logic on IIO context fail for the entire node
> Initialization
